### PR TITLE
fix: fix insert hashes on non-revoked publications

### LINKED ISSUE #72: Insert hashes publication mapping issue on non-revoked publications
The current SQL query uses exact string matching on `name` instead of `date` when mapping a publication to `data_repo_commits` table. This approach, however, does not work in cases where we have revoked publications, since name has a `-01` prefix. We should really be querying by `date` instead.

### PR DESCRIPTION
**Pull request by n-dusan**
## Description (e.g. "Related to ...", etc.)

Closes #72

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly

## Automated tests, benchmarks and linters

You can run the tests, lints and benchmarks that are run on CI locally with:
```sh
just ci
```

[commit messages]: https://conventionalcommits.org/

### CODE REVIEW

File: src/db/models/publication/manager.rs [hunk 1]
```diff
@@ -128,6 +128,28 @@ impl super::TxManager for DatabaseTransaction {
...
+            FROM publication
+            WHERE date = $1 AND stele = $2 AND revoked = 0
+        ";
+        let row = sqlx::query_as::<_, Publication>(statement)
+            .bind(date)
+            .bind(stele)
+            .fetch_one(&mut *self.tx)
+            .await?;
+        Ok(row)
+    }
```
Comment (balsa-sarenac) [inline src/db/models/publication/manager.rs:151]: Just to understand this: Is this doing sort by publication name somehow, or how does it ensure it will get the correct row from publication table? Or is this revoked flag set to true on all old publications that are on the same date, so the only one that is not revoked is then latest one?

**Review by balsa-sarenac — APPROVED** [review]
Just one minor question, looks good!

File: src/db/models/publication/manager.rs (hunk 1 above)
Comment (n-dusan) [reply src/db/models/publication/manager.rs:151]: Yup, revoked flag is set to true for older publications, so this correctly gets the latest (non-revoked publication)

Comment (balsa-sarenac) [reply src/db/models/publication/manager.rs:151]: Awesome, thanks!
